### ISSUE TITLE
Add support for missing-ness 

### ISSUE THREAD

**Issue by daynefiler** [ToxPi/toxpiR#2]
Add functionality to track missing-ness in TxpResult object. 

- [ ] Add `txpMissing` slot to `TxpResult` class; observation by slice matrix (same as `txpSliceScores` ) with the proportion of missing observations 
- [ ] Update txpCalculateScores to calculate missing-ness
- [ ] Add accessors for `txpMissing`
- [ ] Update man page and create examples showing accessors
- [ ] Add tests to cover new missing-ness functionality

**Comment by davidmreif** [comment]
Completed with latest update from /ggplot branch
