### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by patlewig** [ToxPi/toxpiR#5]
Terrific work to create this new package. 
One observation I encountered when performing the install - and might just be specific to me but figured I would report it nonetheless. Using the install.packages and setting dependencies to True still failed to install S4Vectors and BiocGenerics. 
I found I needed to install 'BiocManager' and then use this to install the 2 dependencies. Steps I went through were as follows:
install.packages('BiocManager')
BiocManager::install(c('S4Vectors', 'BiocGenerics'))
install.packages('toxpiR')

**Comment by daynefiler** [comment]
Hey, sorry for the late response. This is really a CRAN issue, as CRAN knows the package relies on Bioconductor packages. I am curious if you already had `BiocManager` installed if `install.packages` could handle the dependency. I did a quick search when you posted this and couldn't find anything other than mentions that "it should work," which falls in line with the package passing all CRAN tests.
